"""
Django settings for dataProcessingServer project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Security — driven by environment variables.
#
# Required in production:
#   DJANGO_SECRET_KEY      — a long, random secret key
#
# Optional (sensible dev defaults apply if not set):
#   DJANGO_DEBUG           — set to "False" / "0" to disable debug mode
#   DJANGO_ALLOWED_HOSTS   — comma-separated list of allowed hostnames
# ---------------------------------------------------------------------------

_SECRET_KEY_ENV = os.getenv('DJANGO_SECRET_KEY')
_IS_DEV = _SECRET_KEY_ENV is None

if _IS_DEV:
    # Development-only fallback — NEVER use this in production.
    SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
else:
    SECRET_KEY = _SECRET_KEY_ENV

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv('DJANGO_DEBUG')
if _debug_env is not None:
    DEBUG = _debug_env.lower() in ('true', '1', 'yes')
else:
    # Default to True in development (when no SECRET_KEY is set).
    DEBUG = _IS_DEV


def _normalize_host(value: str) -> str:
    host = (value or '').strip()
    if not host:
        return ''
    if '://' in host:
        host = (urlparse(host).hostname or '').strip()
    else:
        host = host.split('/')[0].split(':')[0].strip()
    return host.lower()


# ALLOWED_HOSTS
_allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS', '')
_allowed_hosts_from_env = [
    _normalize_host(item) for item in _allowed_hosts_env.split(',') if item.strip()
]

_render_host_candidates = [
    os.getenv('RENDER_EXTERNAL_HOSTNAME', ''),
    os.getenv('RENDER_EXTERNAL_URL', ''),
    os.getenv('RENDER_SERVICE_NAME', ''),
    os.getenv('RAILWAY_PUBLIC_DOMAIN', ''),
    os.getenv('BACKEND_URL', ''),
    os.getenv('API_URL', ''),
    os.getenv('PUBLIC_URL', ''),
    os.getenv('APP_URL', ''),
]
_render_hosts = [
    h for h in (_normalize_host(c) for c in _render_host_candidates) if h
]

_allow_all_hosts = os.getenv('DJANGO_ALLOW_ALL_HOSTS', '').lower() in ('true', '1', 'yes')

if _allow_all_hosts:
    ALLOWED_HOSTS = ['*']
elif _allowed_hosts_from_env:
    ALLOWED_HOSTS = _allowed_hosts_from_env
else:
    # Local dev: allow all localhost variants + Render hosts for production
    ALLOWED_HOSTS = _render_hosts + [
        'localhost',
        '127.0.0.1',
        '[::1]',           # IPv6 localhost
        '.onrender.com',   # Render.com deployments
    ]


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'corsheaders',  # pip install django-cors-headers
    # Local apps
    'api',
]

MIDDLEWARE = [
    # Custom API exception middleware — placed early so API errors return JSON
    'api.middleware.ApiExceptionMiddleware',
    # CorsMiddleware MUST come before CommonMiddleware to handle preflight OPTIONS requests
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dataProcessingServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dataProcessingServer.wsgi.application'


# ---------------------------------------------------------------------------
# CORS — Cross-Origin Resource Sharing
#
# In production set this env var to your actual domains:
#   CORS_ALLOWED_ORIGINS=https://yourfrontend.com,https://yourapi.com
# ---------------------------------------------------------------------------

_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
_cors_from_env = [o.strip() for o in _cors_env.split(',') if o.strip()]

_cors_url_candidates = [
    os.getenv('FRONTEND_URL', ''),
    os.getenv('CLIENT_URL', ''),
    os.getenv('WEB_URL', ''),
]
_cors_from_candidates = [u.strip() for u in _cors_url_candidates if u and u.strip()]

if _cors_from_env:
    CORS_ALLOWED_ORIGINS = _cors_from_env
elif _cors_from_candidates:
    CORS_ALLOWED_ORIGINS = _cors_from_candidates
else:
    # Local dev fallback — never reaches production if env var is set
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:8001',
        'http://127.0.0.1:8001',
    ]

# Allow credentials (cookies, Authorization headers) in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

# Allow all standard + custom headers needed for JSON API calls
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow POST (and other non-simple methods) cross-origin
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ---------------------------------------------------------------------------
# Production security — auto-enabled when DEBUG=False
# (no env vars needed; these activate automatically in production)
# ---------------------------------------------------------------------------

if not DEBUG:
    # Force all traffic over HTTPS
    SECURE_SSL_REDIRECT = True

    # Prevent cookies being sent over HTTP
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Tell browsers to only use HTTPS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Prevent browsers from sniffing content type
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Clickjacking protection
    X_FRAME_OPTIONS = 'DENY'
